site_name: Obelisk Docs
site_url: https://obelus.cc
site_author: Obelus

theme:
  name: material
  language: zh
  favicon: assets/logo.png
  custom_dir: overrides

  font:
    text: Noto Sans Simplified Chinese
    code: JetBrains Mono

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      toggle:
        icon: material/weather-sunny
        name: 切换至深色模式

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      toggle:
        icon: material/weather-night
        name: 切换至浅色模式

  icon:
    logo: material/star-shooting-outline
    repo: fontawesome/brands/github
    annotation: material/comma-circle

  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.top
    - navigation.tabs
    - navigation.indexes
    - navigation.footer
    - toc.follow
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate
    - content.tooltips

nav:
  - 主页: index.md
  - 指南: guide/index.md
  - Ubuntu 安装与配置指南:
    - guide/ubuntu/index.md
    - 获取系统镜像: guide/ubuntu/download-iso.md
    - 制作启动 U 盘: guide/ubuntu/create-boot-usb.md
    - 准备磁盘分区: guide/ubuntu/boot-and-disk.md
    - 安装 Ubuntu: guide/ubuntu/installation.md
    - 配置 Ubuntu:
      - guide/ubuntu/configuration/index.md
      - guide/ubuntu/configuration/update-ubuntu-and-software.md
      - guide/ubuntu/configuration/set-root-password.md
      - guide/ubuntu/configuration/install-nvidia-drivers.md
      - guide/ubuntu/configuration/remove-snap-packages.md
      - guide/ubuntu/configuration/localize-user-directories.md
      - guide/ubuntu/configuration/change-default-boot-entry.md
      - guide/ubuntu/configuration/sync-dual-system-time.md
      - guide/ubuntu/configuration/adjust-high-dpi-scaling.md
      - guide/ubuntu/configuration/install-common-fonts.md
      - guide/ubuntu/configuration/battery-charge-management.md
    - 软件安装与配置:
      - guide/ubuntu/software-setup/index.md
      - Pip: guide/ubuntu/software-setup/pip.md
      - Anaconda: guide/ubuntu/software-setup/conda.md
      - CUDA Toolkit (+cuDNN): guide/ubuntu/software-setup/cuda.md
      - PyTorch: guide/ubuntu/software-setup/pytorch.md
    - 常见问题: guide/ubuntu/faq.md
  - WSL 安装与配置指南:
    - guide/wsl/index.md
    - 安装 WSL: guide/wsl/installation.md
    - 配置 WSL: guide/wsl/configuration.md
    - 管理 WSL: guide/wsl/management.md
    - 软件安装与配置:
      - guide/wsl/software-setup/index.md
      - CUDA Toolkit (+cuDNN): guide/wsl/software-setup/cuda.md
  - OpenGL 安装与配置指南:
    - guide/opengl/index.md
    - 获取 freeglut 与 GLEW: guide/opengl/download-freeglut-and-glew.md
    - Visual Studio 环境配置:
      - guide/opengl/environment-config/index.md
      - 项目级环境配置（单项目）: guide/opengl/environment-config/project-level.md
      - 项目属性表配置（跨项目）: guide/opengl/environment-config/property-sheet.md
    - 设置系统环境变量: guide/opengl/setting-system-environment-variables.md
    - OpenGL 绘图示例: guide/opengl/example.md
  - Android Studio 安装与配置指南:
    - guide/android-studio/index.md
    - 安装 Android Studio: guide/android-studio/installation.md
    - 创建 Android 项目（Phone）: guide/android-studio/create-project.md
  - JetBrains 教育许可证申请指南:
    - guide/jetbrains-educational-license/index.md
    - 注册 JetBrains 账号: guide/jetbrains-educational-license/register-account.md
    - 申请教育许可证（官方文件）: guide/jetbrains-educational-license/apply-license.md
    - 在 JetBrains IDE 激活许可证: guide/jetbrains-educational-license/activate-license.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Obelusod
  analytics:
    provider: google
    property: G-7NRK35CQKM
    feedback:
      title: 此页面是否有帮助？
      ratings:
        - icon: material/emoticon-happy-outline
          name: "很有帮助"
          data: 1
          note: >-
            感谢反馈！
        - icon: material/emoticon-sad-outline
          name: "仍需改进"
          data: 0
          note: >- 
            感谢反馈！

extra_css:
  - stylesheets/extra.css
  - stylesheets/round.css

markdown_extensions:
  - toc:
      toc_depth: 4
      permalink: "#"
      permalink_title: "固定链接"
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
          percent_encode: false
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
          percent_encode: false
  - pymdownx.highlight:
      use_pygments: true
      line_spans: __span
      auto_title: true
      anchor_linenums: true
      pygments_lang_class: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.betterem
  - pymdownx.blocks.caption
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - md_in_html
  - admonition
  - attr_list
  - def_list
  - footnotes
  - tables
  - footnotes

plugins:
  - search:
      lang:
        - zh
        - en
  - glightbox
  - social:
      cards_layout_options:
        font_family: Noto Sans SC

# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json